---
# tasks file for app_lb

- name: Install HAProxy
  become: yes
  ansible.builtin.yum:
    name: haproxy
    state: present

- name: Deploy haproxy.cfg
  become: yes
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'

- name: Allow HAProxy to open outbound connections (SELinux)
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: yes

- name: Enable & start HAProxy
  become: yes
  ansible.builtin.systemd:
    name: haproxy
    enabled: yes
    state: restarted
