---
- name: Get control-plane join command from first control-plane node
  set_fact:
    kubeadm_join_controlplane_cmd: "{{ hostvars[groups['master'][0]].kubeadm_join_controlplane_cmd }}"

- name: Join this node as control-plane
  become: true
  shell: "{{ kubeadm_join_controlplane_cmd }}"
  args:
    creates: /etc/kubernetes/kubelet.conf

- name: Ensure /root/.kube exists
  become: true
  file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Copy admin.conf to /root/.kube/config
  become: true
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: '0600'
    remote_src: true
