---
# hangi paketi kuracağız (RHEL’de çoğu zaman "containerd")
containerd_package_name: "containerd"

# config yolu
containerd_config_path: "/etc/containerd/config.toml"

# kubelet ile uyumlu olsun diye SystemdCgroup kullan
containerd_systemd_cgroup: true

# pause image (ileride kendi local registry'ni yazarsın)
containerd_sandbox_image: "registry.k8s.io/pause:3.9"

# registry mirror’lar (örnek: bastion registry)
# - name: "registry.local"
#   endpoint: "http://registry.local:5000"
containerd_registry_mirrors: []

