---
# tasks file for calico_install
- name: Upload Calico manifest (images rewritten to {{ registry_addr }})
  copy:
    src: "files/calico.yaml"
    dest: /root/calico.yaml

- name: Apply Calico
  command: kubectl apply --validate=false -f /root/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

